#!/usr/bin/env python

import os, re, subprocess, sys

contribdir = os.path.dirname(os.path.realpath(__file__))

with open(contribdir+'/CONTRIBUTORS') as f:
    contributors = {re.sub(r'^.*<(.*)>$',r'\1',line).strip() for line in f.read().splitlines()}

git = subprocess.Popen(['git','log','--format=%ae'],
                       stdout=subprocess.PIPE)
prcontributors = {line.strip() for line in git.stdout.read().splitlines()}

missing = prcontributors.difference(contributors)

if len(missing) == 0:
    print "All contributors are known."
else:
    print "Unkown contributors: " + ', '.join(missing)
    sys.exit(-1)
