#!/usr/bin/env python

import errno, os, re, subprocess, sys

contribdir = os.path.dirname(os.path.realpath(__file__))

def normalize_email(email):
    return re.sub(r'^.*<(.+)>$',r'\1',email).lower()

def read_emails(lines):
    emails = { email.split('#')[0].strip() for email in lines }
    return { normalize_email(email): email for email in emails if email }

with open(contribdir+'/CONTRIBUTORS') as f:
    contributors = read_emails(f.read().splitlines())

git = subprocess.Popen(['git','log','--format=%an <%ae>%n%cn <%ce>'],
                       stdout=subprocess.PIPE)
committers = read_emails(git.stdout.read().splitlines())

missing = [ fullname for email, fullname in committers.iteritems() if email not in contributors ]

if len(missing) != 0:
    print >>sys.stderr, '\n'.join([
        "The following committers are not known contributors:",
        '\n'.join(["* %s" % email for email in sorted(missing, key=str.lower)]),
        "To become a known contributor for MetaBorg projects, you must sign a CLA.",
        "See https://spoofax.readthedocs.io/en/latest/source/dev/contribute.html",
        "for more information on how to do this.",
    ])
    sys.exit(errno.EPERM)
